# Generated by Django 5.0.1 on 2024-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True, verbose_name='Ссылка')),
            ],
        ),
    ]
