# Generated by Django 5.0.1 on 2024-01-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_room_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
