# Generated by Django 5.0.1 on 2024-01-22 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/imagess', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'bmp'])], verbose_name='Картинка'),
        ),
    ]
