# Generated by Django 5.0.1 on 2024-01-22 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_categoryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='categorie_image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'bmp'])], verbose_name='Картинка'),
        ),
    ]
