# Generated by Django 5.0.1 on 2024-01-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_alter_item_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryitem',
            old_name='image',
            new_name='images',
        ),
    ]
