# Generated by Django 5.0.1 on 2024-01-23 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_alter_categoryitem_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='Текст сообщения')),
                ('date_added', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, max_length=300, verbose_name='дата и время добавления')),
                ('room', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.room', verbose_name='Комната')),
                ('user', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-date_added', '-room'),
            },
        ),
    ]
