# Generated by Django 5.0.1 on 2024-01-24 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'bmp'])], verbose_name='Картинка'),
        ),
    ]
